spring.application.name=electricity-consumption
spring.datasource.url=jdbc:postgresql://localhost:5432/enefit_backend
spring.datasource.username=postgres
spring.datasource.password=parool123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.access.secret=U6z@t!8xFwLqP#2vGmYh$9NsD%3aKZcR
jwt.refresh.secret=J5p&Qx!7vMZdN@3GgKt$L9YsT%2bFwAc
jwt.access.expiration=900000
jwt.refresh.expiration=2592000000
logging.level.org.springframework.security=DEBUG
logging.level.com.example.electricity_consumption=DEBUG
elering.base-url=https://dashboard.elering.ee
